# Generated by Django 5.2 on 2025-05-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_hashtag_event_likes_event_hashtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='onsite_payement',
            field=models.BooleanField(default=False),
        ),
    ]
