# Generated by Django 5.2 on 2025-05-09 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_event_onsite_payement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='cover_image_url',
            new_name='cover_image_url_old',
        ),
    ]
