# Generated by Django 5.2 on 2025-05-09 06:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_rename_cover_image_url_event_cover_image_url_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cover_image_url',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, size=None),
        ),
    ]
