# Generated by Django 5.2 on 2025-05-09 06:08

from django.db import migrations

def convert_url_to_array(apps, schema_editor):
    Event = apps.get_model('event', 'Event')
    for event in Event.objects.all():
        if event.cover_image_url_old:
            event.cover_image_url = [event.cover_image_url_old]
            event.save()

class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_event_cover_image_url'),
    ]

    operations = [
    migrations.RunPython(convert_url_to_array),

    ]
