# Generated by Django 5.2 on 2025-05-09 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20250509_0608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='cover_image_url_old',
        ),
    ]
