# Generated by Django 5.2 on 2025-05-15 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='userticket',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
