# Generated by Django 5.2 on 2025-05-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_ticket_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
