# Generated by Django 5.2 on 2025-05-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_created_at_profile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_photo',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_photo_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
