# Generated by Django 5.2 on 2025-05-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_profile_profile_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationprofile',
            name='verification_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='verification_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('denied', 'Denied')], default='pending', max_length=20),
        ),
    ]
