# Generated by Django 5.2 on 2025-04-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationprofile',
            name='logo_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
