# Generated by Django 5.2 on 2025-05-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('online', 'ONLINE'), ('onsite', 'ONSITE')], default='online', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='tx_ref',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
