# Generated by Django 5.2 on 2025-05-15 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_userticket_used'),
        ('payment', '0003_payment_method_alter_payment_tx_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='single_payments', to='event.ticket'),
        ),
        migrations.CreateModel(
            name='PaymentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payment.payment')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.ticket')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='tickets',
            field=models.ManyToManyField(related_name='payments', through='payment.PaymentItem', to='event.ticket'),
        ),
    ]
