# Generated by Django 5.2 on 2025-05-16 08:35

from django.db import migrations, models
from django import utils

def populate_created_at(apps, schema_editor):
    Payment = apps.get_model('payment', 'Payment')
    PaymentItem = apps.get_model('payment', 'PaymentItem')
    now = utils.timezone.now()

    for payment in Payment.objects.filter(created_at__isnull=True):
        payment.created_at = now
        payment.save(update_fields=["created_at"])
        
    for paymentItem in PaymentItem.objects.filter(created_at__isnull=True):
        paymentItem.created_at = now
        paymentItem.save(update_fields=["created_at"])
        
    

class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_remove_payment_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='paymentitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(populate_created_at),
    ]
